from datetime import datetime
import time
clock = datetime.now()

print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
clock= datetime.now()
print("the date and time is", clock)
time.sleep(1)
